# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  NODE_VERSION: '10.x'

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ env.NODE_VERSION }}d
    - name: npm install, build
      run: |
        npm install
        npm run build --if-present
    - name: Verify build
      run: |
        pwd
        ls -al .
        head output.svg
    - name: neenjaw/compile-mermaid-markdown-action
      uses: neenjaw/compile-mermaid-markdown-action@0.2.4dd
    - name: Verify neenjaw/compile-mermaid-markdown-action
      run: ls -al .
